#! /bin/bash

DEPENDENCIES=`command -v git curl wget jq js-beautify | wc -l`
# Check if a URL is provided as an argument
if [ $# -ne 1 ]; then
  echo "Usage: $0 <URL>"
  exit 1
# Check dependencies
elif [ $DEPENDENCIES -ne 5 ]; then
    echo "Please install wget, git, curl, jq and js-beautify."
    exit 1
fi

# Generate the URL for the Wayback Machine CDX API
CDX_URL="https://web.archive.org/cdx/search/cdx?url=$1&collapse=digest&output=json&fl=timestamp,original,statuscode,digest"

# Make a request to the Wayback Machine CDX API and capture the RESPONSE
printf "\r[+] Checking archive.org..."
RESPONSE=$(wget "$CDX_URL" -q -O /tmp/hview.txt && cat /tmp/hview.txt && rm /tmp/hview.txt)
EMPTY="[]"

# Check if the RESPONSE contains any SNAPSHOTS
if [[ "$RESPONSE" != "$EMPTY" || "$RESPONSE"!="" ]]; then

  # Extract the archive URLs from the RESPONSE
  SNAPSHOTS=($(echo "$RESPONSE" | jq -r '.[] | select(.[2] == "200") | "\(.[0])/\(.[1]) \(.[3])"' | sort -k2 -u | cut -d ' ' -f1 | sort))
  DOMAIN=`echo $1 | awk -F'[/:]' '{print $4}'`
  DIR="${DOMAIN}_`date +%s`";


  LENGTH="${#SNAPSHOTS[@]}";
  COUNT=0
  
  if [ ! $LENGTH -gt 0 ]; then
    printf "\r[-] No archive has found :(\n"
    exit 1
  fi

  mkdir -p $DIR && cd $DIR && git init > /dev/null;
  # Loop through the archive URLs and fetch each SNAPSHOT
  for SNAPSHOT in "${SNAPSHOTS[@]}"; do
    DATE=$(echo $SNAPSHOT | cut -d '/' -f 1 | sed 's/\(....\)\(..\)\(..\)\(..\)\(..\)\(..\)/\1-\2-\3-\4:\5:\6/')
    FILENAME=$(basename "${SNAPSHOT/\?*/}"); # app.js

    # Get content
    curl -s -m 15 --max-filesize 30M "https://web.archive.org/web/$SNAPSHOT" | js-beautify > $FILENAME 2>/dev/null;

    # Commit changes
    git add $FILENAME && git commit -m "$DATE" > /dev/null;

    COUNT=$(($COUNT+1))
    printf "\r                                            "
    printf "\r[+] Downloading $COUNT/$LENGTH"

  done

  printf "\r                                            "
  printf "\r[+] $count file(s) successfully saved at $DIR                     \n"
  exit 0

else
  printf "\r[-] No archive has found :(\n"
  exit 1
fi
